
"""add_post_status_publish_at

Revision ID: e9e1a0d6e727
Revises: 45d025f578ae
Create Date: 2025-08-18 11:22:14.120520
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'e9e1a0d6e727'
down_revision: Union[str, None] = '45d025f578ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('status', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('publish_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'publish_at')
    op.drop_column('posts', 'status')
    # ### end Alembic commands ###
